from pydantic import BaseModel
from typing import Optional, Any


class RealDataInput(BaseModel):
    ID: int
    ACTIVIT2: str
    VOCATION: str
    TYPERS: int
    ANCIENNETE: int
    ADOSS: str
    CARACT1: str
    CARACT2: float
    CARACT3: float
    INDEM1: str
    DUREE_REQANEUF: float
    CARACT4: str
    CARACT5: int
    TYPBAT1: float
    INDEM2: str
    TYPBAT2: int
    FRCH1: int
    FRCH2: float
    DEROG1: str
    DEROG2: str
    DEROG3: str
    DEROG4: str
    DEROG5: str
    DEROG6: str
    DEROG7: str
    DEROG8: str
    DEROG9: str
    DEROG10: str
    DEROG11: str
    DEROG12: float
    DEROG13: float
    DEROG14: float
    DEROG15: float
    DEROG16: float
    TAILLE1: str
    TAILLE2: str
    CA1: int
    CA2: int
    CA3: int
    KAPITAL1: int
    KAPITAL2: int
    KAPITAL3: int
    KAPITAL4: int
    KAPITAL5: int
    KAPITAL6: int
    KAPITAL7: int
    KAPITAL8: int
    KAPITAL9: int
    KAPITAL10: int
    KAPITAL11: float
    KAPITAL12: int
    KAPITAL13: int
    KAPITAL14: int
    KAPITAL15: float
    KAPITAL16: float
    KAPITAL17: float
    KAPITAL18: float
    KAPITAL19: float
    KAPITAL20: float
    KAPITAL21: float
    KAPITAL22: float
    KAPITAL23: float
    KAPITAL24: float
    KAPITAL25: int
    KAPITAL26: int
    KAPITAL27: int
    KAPITAL28: int
    KAPITAL29: float
    KAPITAL30: float
    KAPITAL31: float
    KAPITAL32: int
    KAPITAL33: float
    KAPITAL34: str
    KAPITAL35: str
    KAPITAL36: str
    KAPITAL37: str
    KAPITAL38: str
    KAPITAL39: str
    KAPITAL40: str
    KAPITAL41: str
    KAPITAL42: str
    KAPITAL43: str
    SURFACE1: int
    SURFACE2: int
    SURFACE3: float
    SURFACE4: int
    SURFACE5: int
    SURFACE6: int
    SURFACE7: float
    SURFACE8: float
    SURFACE9: float
    SURFACE10: float
    SURFACE11: float
    SURFACE12: int
    SURFACE13: int
    SURFACE14: int
    SURFACE15: int
    SURFACE16: int
    SURFACE17: int
    SURFACE18: float
    SURFACE19: float
    SURFACE20: int
    SURFACE21: int
    NBBAT1: int
    NBBAT2: int
    NBBAT3: int
    NBBAT4: int
    NBBAT5: int
    NBBAT6: int
    NBBAT7: int
    NBBAT8: int
    NBBAT9: int
    NBBAT10: int
    NBBAT11: int
    NBBAT13: int
    NBBAT14: int
    TAILLE3: int
    TAILLE4: int
    NBSINCONJ: float
    NBSINSTRT: float
    COEFASS: str
    RISK1: float
    RISK2: float
    RISK3: float
    RISK4: float
    RISK5: float
    RISK6: float
    RISK7: float
    RISK8: float
    RISK9: float
    RISK10: str
    RISK11: str
    RISK12: float
    RISK13: float
    EQUIPEMENT1: int
    EQUIPEMENT2: float
    EQUIPEMENT3: int
    EQUIPEMENT4: int
    EQUIPEMENT5: float
    EQUIPEMENT6: int
    EQUIPEMENT7: int
    DISTANCE_111: float
    DISTANCE_112: float
    DISTANCE_121: float
    DISTANCE_122: float
    DISTANCE_123: float
    DISTANCE_124: float
    DISTANCE_131: float
    DISTANCE_132: float
    DISTANCE_133: float
    DISTANCE_141: float
    DISTANCE_142: float
    DISTANCE_211: float
    DISTANCE_212: float
    DISTANCE_213: float
    DISTANCE_221: float
    DISTANCE_222: float
    DISTANCE_223: float
    DISTANCE_231: float
    DISTANCE_242: float
    DISTANCE_243: float
    DISTANCE_244: float
    DISTANCE_311: float
    DISTANCE_312: float
    DISTANCE_313: float
    DISTANCE_321: float
    DISTANCE_322: float
    DISTANCE_323: float
    DISTANCE_324: float
    DISTANCE_331: float
    DISTANCE_332: float
    DISTANCE_333: float
    DISTANCE_334: float
    DISTANCE_335: float
    DISTANCE_411: float
    DISTANCE_412: float
    DISTANCE_421: float
    DISTANCE_422: float
    DISTANCE_423: float
    DISTANCE_511: float
    DISTANCE_512: float
    DISTANCE_521: float
    DISTANCE_522: float
    DISTANCE_523: float
    PROPORTION_11: str
    PROPORTION_12: str
    PROPORTION_13: str
    PROPORTION_14: str
    PROPORTION_21: str
    PROPORTION_22: str
    PROPORTION_23: str
    PROPORTION_24: str
    PROPORTION_31: str
    PROPORTION_32: str
    PROPORTION_33: str
    PROPORTION_41: str
    PROPORTION_42: str
    PROPORTION_51: str
    PROPORTION_52: str
    MEN: str
    MEN_PAUV: str
    MEN_1IND: str
    MEN_5IND: str
    MEN_PROP: str
    MEN_FMP: str
    MEN_COLL: str
    MEN_MAIS: str
    LOG_AVA1: str
    LOG_A1_A2: str
    LOG_A2_A3: str
    LOG_APA3: str
    LOG_INC: str
    LOG_SOC: str
    IND: str
    IND_0_Y1: str
    IND_Y1_Y2: str
    IND_Y2_Y3: str
    IND_Y3_Y4: str
    IND_Y4_Y5: str
    IND_Y5_Y6: str
    IND_Y6_Y7: str
    IND_Y7_Y8: str
    IND_Y8_Y9: str
    IND_Y9: str
    IND_INC: str
    IND_SNV: str
    MEN_SURF: str
    DISTANCE_1: float
    DISTANCE_2: float
    ALTITUDE_1: float
    ALTITUDE_2: str
    ALTITUDE_3: str
    ALTITUDE_4: str
    ALTITUDE_5: str
    BDTOPO_BAT_MAX_HAUTEUR_MAX: float
    HAUTEUR: float
    HAUTEUR_MAX: float
    BDTOPO_BAT_MAX_HAUTEUR: float
    ZONE_VENT: float
    NB_CASERNES: str
    NBJTX25_MM_A: float
    NBJTX25_MMAX_A: float
    NBJTX25_MSOM_A: float
    NBJTX0_MM_A: float
    NBJTX0_MMAX_A: float
    NBJTX0_MSOM_A: float
    NBJTXI27_MM_A: float
    NBJTXI27_MMAX_A: float
    NBJTXI27_MSOM_A: float
    NBJTXS32_MM_A: float
    NBJTXS32_MMAX_A: float
    NBJTXS32_MSOM_A: float
    NBJTXI20_MM_A: float
    NBJTXI20_MMAX_A: float
    NBJTXI20_MSOM_A: float
    NBJTX30_MM_A: float
    NBJTX30_MMAX_A: float
    NBJTX30_MSOM_A: float
    NBJTX35_MM_A: float
    NBJTX35_MMAX_A: float
    NBJTX35_MSOM_A: float
    NBJTN10_MM_A: float
    NBJTN10_MMAX_A: float
    NBJTN10_MSOM_A: float
    NBJTNI10_MM_A: float
    NBJTNI10_MMAX_A: float
    NBJTNI10_MSOM_A: float
    NBJTN5_MM_A: float
    NBJTN5_MMAX_A: float
    NBJTN5_MSOM_A: float
    NBJTNS25_MM_A: float
    NBJTNS25_MMAX_A: float
    NBJTNS25_MSOM_A: float
    NBJTNI15_MM_A: float
    NBJTNI15_MMAX_A: float
    NBJTNI15_MSOM_A: float
    NBJTNI20_MM_A: float
    NBJTNI20_MMAX_A: float
    NBJTNI20_MSOM_A: float
    NBJTNS20_MM_A: float
    NBJTNS20_MMAX_A: float
    NBJTNS20_MSOM_A: float
    NBJTMS24_MM_A: float
    NBJTMS24_MMAX_A: float
    NBJTMS24_MSOM_A: float
    TAMPLIAB_VOR_MM_A: float
    TAMPLIAB_VOR_MMAX_A: float
    TAMPLIM_VOR_MM_A: float
    TAMPLIM_VOR_MMAX_A: float
    TM_VOR_MM_A: float
    TM_VOR_MMAX_A: float
    TMM_VOR_MM_A: float
    TMM_VOR_MMAX_A: float
    TMMAX_VOR_MM_A: float
    TMMAX_VOR_MMAX_A: float
    TMMIN_VOR_MM_A: float
    TMMIN_VOR_MMAX_A: float
    TN_VOR_MM_A: float
    TN_VOR_MMAX_A: float
    TNAB_VOR_MM_A: float
    TNAB_VOR_MMAX_A: float
    TNMAX_VOR_MM_A: float
    TNMAX_VOR_MMAX_A: float
    TX_VOR_MM_A: float
    TX_VOR_MMAX_A: float
    TXAB_VOR_MM_A: float
    TXAB_VOR_MMAX_A: float
    TXMIN_VOR_MM_A: float
    TXMIN_VOR_MMAX_A: float
    NBJFF10_MM_A: float
    NBJFF10_MMAX_A: float
    NBJFF10_MSOM_A: float
    NBJFF16_MM_A: float
    NBJFF16_MMAX_A: float
    NBJFF16_MSOM_A: float
    NBJFF28_MM_A: float
    NBJFF28_MMAX_A: float
    NBJFF28_MSOM_A: float
    NBJFXI3S10_MM_A: float
    NBJFXI3S10_MMAX_A: float
    NBJFXI3S10_MSOM_A: float
    NBJFXI3S16_MM_A: float
    NBJFXI3S16_MMAX_A: float
    NBJFXI3S16_MSOM_A: float
    NBJFXI3S28_MM_A: float
    NBJFXI3S28_MMAX_A: float
    NBJFXI3S28_MSOM_A: float
    NBJFXY8_MM_A: float
    NBJFXY8_MMAX_A: float
    NBJFXY8_MSOM_A: float
    NBJFXY10_MM_A: float
    NBJFXY10_MMAX_A: float
    NBJFXY10_MSOM_A: float
    NBJFXY15_MM_A: float
    NBJFXY15_MMAX_A: float
    NBJFXY15_MSOM_A: float
    FFM_VOR_MM_A: float
    FFM_VOR_MMAX_A: float
    FXI3SAB_VOR_MM_A: float
    FXI3SAB_VOR_MMAX_A: float
    FXIAB_VOR_MM_A: float
    FXIAB_VOR_MMAX_A: float
    FXYAB_VOR_MM_A: float
    FXYAB_VOR_MMAX_A: float
    FFM_VOR_COM_MM_A_Y: str
    FFM_VOR_COM_MMAX_A_Y: str
    FXI3SAB_VOR_COM_MM_A_Y: str
    FXI3SAB_VOR_COM_MMAX_A_Y: str
    NBJRR50_MM_A: float
    NBJRR50_MMAX_A: float
    NBJRR50_MSOM_A: float
    NBJRR1_MM_A: float
    NBJRR1_MMAX_A: float
    NBJRR1_MSOM_A: float
    NBJRR5_MM_A: float
    NBJRR5_MMAX_A: float
    NBJRR5_MSOM_A: float
    NBJRR10_MM_A: float
    NBJRR10_MMAX_A: float
    NBJRR10_MSOM_A: float
    NBJRR30_MM_A: float
    NBJRR30_MMAX_A: float
    NBJRR30_MSOM_A: float
    NBJRR100_MM_A: float
    NBJRR100_MMAX_A: float
    NBJRR100_MSOM_A: float
    RR_VOR_MM_A: float
    RR_VOR_MMAX_A: float
    RRAB_VOR_MM_A: float
    RRAB_VOR_MMAX_A: float
    ANNEE_ASSURANCE: float
    ESPINSEE: float
    AN_EXERC: str
    ZONE: int