from pydantic import BaseModel


class CMPredictionInput(BaseModel):
    ID: int
    ACTIVIT2: int
    VOCATION: int
    TYPERS: int
    ANCIENNETE: int
    ADOSS: int
    CARACT1: int
    CARACT2: int
    CARACT3: int
    INDEM1: int
    DUREE_REQANEUF: int
    CARACT4: int
    CARACT5: int
    INDEM2: int
    TYPBAT2: int
    DEROG1: int
    DEROG2: int
    DEROG3: int
    DEROG4: int
    DEROG5: int
    DEROG6: int
    DEROG7: int
    DEROG8: int
    DEROG9: int
    DEROG10: int
    DEROG11: int
    DEROG15: int
    TAILLE1: int
    TAILLE2: int
    CA1: int
    CA2: int
    CA3: int
    KAPITAL1: int
    KAPITAL2: int
    KAPITAL3: int
    KAPITAL4: int
    KAPITAL5: int
    KAPITAL6: int
    KAPITAL7: int
    KAPITAL8: int
    KAPITAL9: int
    KAPITAL10: int
    KAPITAL11: int
    KAPITAL12: int
    KAPITAL13: int
    KAPITAL14: int
    KAPITAL15: int
    KAPITAL16: int
    KAPITAL17: int
    KAPITAL18: int
    KAPITAL19: int
    KAPITAL20: int
    KAPITAL21: int
    KAPITAL22: int
    KAPITAL23: int
    KAPITAL24: int
    KAPITAL25: int
    KAPITAL26: int
    KAPITAL27: int
    KAPITAL28: int
    KAPITAL29: int
    KAPITAL30: int
    KAPITAL31: int
    KAPITAL32: int
    KAPITAL33: int
    KAPITAL34: int
    KAPITAL35: int
    KAPITAL36: int
    KAPITAL37: int
    KAPITAL38: int
    KAPITAL39: int
    KAPITAL40: int
    KAPITAL41: int
    KAPITAL42: int
    KAPITAL43: int
    SURFACE1: int
    SURFACE2: int
    SURFACE3: int
    SURFACE4: int
    SURFACE5: int
    SURFACE6: int
    SURFACE7: int
    SURFACE8: int
    SURFACE9: int
    SURFACE10: int
    SURFACE11: int
    SURFACE12: int
    SURFACE13: int
    SURFACE14: int
    SURFACE15: int
    SURFACE16: int
    SURFACE17: int
    SURFACE18: int
    SURFACE19: int
    SURFACE20: int
    SURFACE21: int
    NBBAT1: int
    NBBAT2: int
    NBBAT3: int
    NBBAT4: int
    NBBAT5: int
    NBBAT6: int
    NBBAT7: int
    NBBAT8: int
    NBBAT9: int
    NBBAT10: int
    NBBAT11: int
    NBBAT13: int
    NBBAT14: int
    TAILLE3: int
    TAILLE4: int
    NBSINCONJ: int
    NBSINSTRT: int
    COEFASS: int
    RISK1: int
    RISK2: int
    RISK3: int
    RISK4: int
    RISK5: int
    RISK7: int
    RISK10: int
    RISK11: int
    EQUIPEMENT1: int
    EQUIPEMENT3: int
    EQUIPEMENT4: int
    EQUIPEMENT6: int
    EQUIPEMENT7: int
    DISTANCE_111: int
    DISTANCE_112: int
    DISTANCE_121: int
    DISTANCE_122: int
    DISTANCE_123: int
    DISTANCE_124: int
    DISTANCE_131: int
    DISTANCE_132: int
    DISTANCE_133: int
    DISTANCE_141: int
    DISTANCE_142: int
    DISTANCE_211: int
    DISTANCE_212: int
    DISTANCE_213: int
    DISTANCE_221: int
    DISTANCE_222: int
    DISTANCE_223: int
    DISTANCE_231: int
    DISTANCE_242: int
    DISTANCE_243: int
    DISTANCE_244: int
    DISTANCE_311: int
    DISTANCE_312: int
    DISTANCE_313: int
    DISTANCE_321: int
    DISTANCE_322: int
    DISTANCE_323: int
    DISTANCE_324: int
    DISTANCE_331: int
    DISTANCE_332: int
    DISTANCE_333: int
    DISTANCE_334: int
    DISTANCE_335: int
    DISTANCE_411: int
    DISTANCE_412: int
    DISTANCE_421: int
    DISTANCE_422: int
    DISTANCE_423: int
    DISTANCE_511: int
    DISTANCE_512: int
    DISTANCE_521: int
    DISTANCE_522: int
    DISTANCE_523: int
    PROPORTION_11: int
    PROPORTION_12: int
    PROPORTION_13: int
    PROPORTION_14: int
    PROPORTION_21: int
    PROPORTION_22: int
    PROPORTION_23: int
    PROPORTION_24: int
    PROPORTION_31: int
    PROPORTION_32: int
    PROPORTION_33: int
    PROPORTION_41: int
    PROPORTION_42: int
    PROPORTION_51: int
    PROPORTION_52: int
    MEN: int
    MEN_PAUV: int
    MEN_1IND: int
    MEN_5IND: int
    MEN_PROP: int
    MEN_FMP: int
    MEN_COLL: int
    MEN_MAIS: int
    LOG_AVA1: int
    LOG_A1_A2: int
    LOG_A2_A3: int
    LOG_APA3: int
    LOG_INC: int
    LOG_SOC: int
    IND: int
    IND_0_Y1: int
    IND_Y1_Y2: int
    IND_Y2_Y3: int
    IND_Y3_Y4: int
    IND_Y4_Y5: int
    IND_Y5_Y6: int
    IND_Y6_Y7: int
    IND_Y7_Y8: int
    IND_Y8_Y9: int
    IND_Y9: int
    IND_INC: int
    IND_SNV: int
    MEN_SURF: int
    DISTANCE_1: int
    DISTANCE_2: int
    ALTITUDE_1: int
    ALTITUDE_2: int
    ALTITUDE_3: int
    ALTITUDE_4: int
    ALTITUDE_5: int
    BDTOPO_BAT_MAX_HAUTEUR_MAX: int
    HAUTEUR: int
    HAUTEUR_MAX: int
    BDTOPO_BAT_MAX_HAUTEUR: int
    ZONE_VENT: int
    NB_CASERNES: int
    NBJTX25_MM_A: int
    NBJTX25_MMAX_A: int
    NBJTX25_MSOM_A: int
    NBJTX0_MM_A: int
    NBJTX0_MMAX_A: int
    NBJTX0_MSOM_A: int
    NBJTXI27_MM_A: int
    NBJTXI27_MMAX_A: int
    NBJTXI27_MSOM_A: int
    NBJTXS32_MM_A: int
    NBJTXS32_MMAX_A: int
    NBJTXS32_MSOM_A: int
    NBJTXI20_MM_A: int
    NBJTXI20_MMAX_A: int
    NBJTXI20_MSOM_A: int
    NBJTX30_MM_A: int
    NBJTX30_MMAX_A: int
    NBJTX30_MSOM_A: int
    NBJTX35_MM_A: int
    NBJTX35_MMAX_A: int
    NBJTX35_MSOM_A: int
    NBJTN10_MM_A: int
    NBJTN10_MMAX_A: int
    NBJTN10_MSOM_A: int
    NBJTNI10_MM_A: int
    NBJTNI10_MMAX_A: int
    NBJTNI10_MSOM_A: int
    NBJTN5_MM_A: int
    NBJTN5_MMAX_A: int
    NBJTN5_MSOM_A: int
    NBJTNS25_MM_A: int
    NBJTNS25_MMAX_A: int
    NBJTNS25_MSOM_A: int
    NBJTNI15_MM_A: int
    NBJTNI15_MMAX_A: int
    NBJTNI15_MSOM_A: int
    NBJTNI20_MM_A: int
    NBJTNI20_MMAX_A: int
    NBJTNI20_MSOM_A: int
    NBJTNS20_MM_A: int
    NBJTNS20_MMAX_A: int
    NBJTNS20_MSOM_A: int
    NBJTMS24_MM_A: int
    NBJTMS24_MMAX_A: int
    NBJTMS24_MSOM_A: int
    TAMPLIAB_VOR_MM_A: int
    TAMPLIAB_VOR_MMAX_A: int
    TAMPLIM_VOR_MM_A: int
    TAMPLIM_VOR_MMAX_A: int
    TM_VOR_MM_A: int
    TM_VOR_MMAX_A: int
    TMM_VOR_MM_A: int
    TMM_VOR_MMAX_A: int
    TMMAX_VOR_MM_A: int
    TMMAX_VOR_MMAX_A: int
    TMMIN_VOR_MM_A: int
    TMMIN_VOR_MMAX_A: int
    TN_VOR_MM_A: int
    TN_VOR_MMAX_A: int
    TNAB_VOR_MM_A: int
    TNAB_VOR_MMAX_A: int
    TNMAX_VOR_MM_A: int
    TNMAX_VOR_MMAX_A: int
    TX_VOR_MM_A: int
    TX_VOR_MMAX_A: int
    TXAB_VOR_MM_A: int
    TXAB_VOR_MMAX_A: int
    TXMIN_VOR_MM_A: int
    TXMIN_VOR_MMAX_A: int
    NBJFF10_MM_A: int
    NBJFF10_MMAX_A: int
    NBJFF10_MSOM_A: int
    NBJFF16_MM_A: int
    NBJFF16_MMAX_A: int
    NBJFF16_MSOM_A: int
    NBJFF28_MM_A: int
    NBJFF28_MMAX_A: int
    NBJFF28_MSOM_A: int
    NBJFXI3S10_MM_A: int
    NBJFXI3S10_MMAX_A: int
    NBJFXI3S10_MSOM_A: int
    NBJFXI3S16_MM_A: int
    NBJFXI3S16_MMAX_A: int
    NBJFXI3S16_MSOM_A: int
    NBJFXI3S28_MM_A: int
    NBJFXI3S28_MMAX_A: int
    NBJFXI3S28_MSOM_A: int
    NBJFXY8_MM_A: int
    NBJFXY8_MMAX_A: int
    NBJFXY8_MSOM_A: int
    NBJFXY10_MM_A: int
    NBJFXY10_MMAX_A: int
    NBJFXY10_MSOM_A: int
    NBJFXY15_MM_A: int
    NBJFXY15_MMAX_A: int
    NBJFXY15_MSOM_A: int
    FFM_VOR_MM_A: int
    FFM_VOR_MMAX_A: int
    FXI3SAB_VOR_MM_A: int
    FXI3SAB_VOR_MMAX_A: int
    FXIAB_VOR_MM_A: int
    FXIAB_VOR_MMAX_A: int
    FXYAB_VOR_MM_A: int
    FXYAB_VOR_MMAX_A: int
    FFM_VOR_COM_MM_A_Y: int
    FFM_VOR_COM_MMAX_A_Y: int
    FXI3SAB_VOR_COM_MM_A_Y: int
    FXI3SAB_VOR_COM_MMAX_A_Y: int
    NBJRR50_MM_A: int
    NBJRR50_MMAX_A: int
    NBJRR50_MSOM_A: int
    NBJRR1_MM_A: int
    NBJRR1_MMAX_A: int
    NBJRR1_MSOM_A: int
    NBJRR5_MM_A: int
    NBJRR5_MMAX_A: int
    NBJRR5_MSOM_A: int
    NBJRR10_MM_A: int
    NBJRR10_MMAX_A: int
    NBJRR10_MSOM_A: int
    NBJRR30_MM_A: int
    NBJRR30_MMAX_A: int
    NBJRR30_MSOM_A: int
    NBJRR100_MM_A: int
    NBJRR100_MMAX_A: int
    NBJRR100_MSOM_A: int
    RR_VOR_MM_A: int
    RR_VOR_MMAX_A: int
    RRAB_VOR_MM_A: int
    RRAB_VOR_MMAX_A: int
    ANNEE_ASSURANCE: int
    AN_EXERC: int
    ZONE: int