name: Tests CM Pipeline

on:
  workflow_dispatch:  # ➜ Permet de lancer manuellement

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r cm/requirements.txt

      - name: Run tests
        run: |
          pytest cm/tests
